# Site settings
title: Abdul Jawad
general_email: jawadefaj006@gmail.com
academic_email: abjawad@ucsc.edu

description: > # this means to ignore newlines until "baseurl:"
  I am a Ph.D. candidate at UCSC. My research focuses on modeling human driven vehicle for autonomous vehicle testing. 

baseurl: "" # the subpath of your site, e.g. /blog/

url: "" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: jawadefaj
linkedin_username: abdul-jawad-efaj
facebook_username: jawadefaj
researchgate_username: Abdul-Jawad-5
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
