# Site settings
title: Saidul Alam Chowdhury
general_email: saidul.cuet105@gmail.com
academic_email: saidul105@inu.ac.kr

description: > # this means to ignore newlines until "baseurl:"
  I am a Ph.D. candidate at Incheon National University, South Korea. My research focuses on power electronics and analog, digital and mixed signal circuits design for wireless power transfer applications: Portable Devices, Electric Vehicle, Automatic Guided Vehicle.    

baseurl: "" # the subpath of your site, e.g. /blog/

url: "" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: saidul105
linkedin_username: saidul-alam-chowdhury
researchgate_username: Saidul-Alam-Chowdhury
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
